// assets/profile/components/provider-app.jsx
import React from 'react'
import {Route, Switch} from 'react-router-dom'

import {SETTINGS, PROGRAMS, PUBLICATIONS, MESSAGES, SERVICES} from '../utils/routes'

import ProviderMenu from './menu/provider-menu'

import Settings from './settings/settings'
import Programs from './programs/programs'
import Publications from './publications/publications'
import Messages from './messages/messages'
import Services from './services/services'

const ProviderApp = () => {
  return (
    <div className="main_profile">
      <h2 className="title">Личный кабинет провайдера</h2>
      <ProviderMenu/>

      <Switch>
        <Route exact name="profile.settings" path={SETTINGS} component={Settings}/>
        <Route exact name="profile.programs" path={PROGRAMS} component={Programs}/>
        <Route exact name="profile.publications" path={PUBLICATIONS} component={Publications}/>
        <Route exact name="profile.messages" path={MESSAGES} component={Messages}/>
        <Route exact name="profile.services" path={SERVICES} component={Services}/>
      </Switch>
    </div>
  )
}

export default ProviderApp

// assets/components/profile/ProviderApp.vue
<template lang="pug">
  #profile-app
    .profile
      h1 Личный кабинет провайдера
      .profile-menu
        menu-item(v-bind:route="'settings'" v-bind:text="'Настройки профиля'")
        menu-item(v-bind:route="'programs'" v-bind:text="'Программы обучения'")
        menu-item(v-bind:route="'publications'" v-bind:text="'Публикации'")
        menu-item(v-bind:route="'messages'" v-bind:text="'Сообщения'")
        menu-item(v-bind:route="'services'" v-bind:text="'Платные услуги, документы'")
      .profile-content
        router-view
</template>

<script>
  import menuItem from './components/menuItem';

  export default {
    name: 'providerApp',
    components: {
      menuItem,
    },
  }
</script>
