// assets/components/profile/UserApp.vue
<template lang="pug">
  #profile-app
    .profile
      h1 Личный кабинет обучающегося
      .profile-menu
        menu-item(v-bind:route="'settings'" v-bind:text="'Настройки профиля'")
        menu-item(v-bind:route="'messages'" v-bind:text="'Сообщения'")
        menu-item(v-bind:route="'training'" v-bind:text="'Мое обучение'")
      .profile-content
        router-view
</template>

<script>
  import menuItem from './components/menuItem';

  export default {
    name: 'userApp',
    components: {
      menuItem,
    },
  }
</script>

// assets/pages/profile/components/user-app.jsx
import React from 'react'
import {Route, Switch} from 'react-router-dom'

import {LEARN, MESSAGES, SETTINGS} from '@/utils/profile/routes'

import UserMenu from './menu/user-menu'

import UserSettings from './settings/user/user-settings'
import Messages from './messages/messages'
import Learn from './learn/learn'

import css from './index.scss?module'


const UserApp = () => {
  return (
    <div className={ css.mainProfile }>
      <h2 className="title">Личный кабинет обучающегося</h2>
      <UserMenu/>

      <Switch>
        <Route exact name="profile.settings" path={SETTINGS} component={UserSettings}/>
        <Route exact name="profile.messages" path={MESSAGES} component={Messages}/>
        <Route exact name="profile.learn" path={LEARN} component={Learn}/>
      </Switch>
    </div>
  )
}

export default UserApp
